name: Publish Docker image to GitHub Container Registry
 
on: [push]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Build, Tag and Push Docker Image to GHCR
        uses: GlueOps/github-actions-build-push-containers@a963c30afbaef6fd551270f351ee6070bd74e10c # v0.1.1